### PR TITLE
URI path format specifiers; doc tweak

### PR DESCRIPTION
**Pull request by ethus3h**
Added base64 versions of Spotify URIs as path format specifiers; tweaked documentation.

NOTE: This is my first exploration of NodeJS and CoffeeScript, so I’m not sure if I’ve done this correctly; I’d appreciate if someone could take a quick look at what I changed and make sure it does what I said it does in the README. Thanks :)

### CODE REVIEW

**Comment by kelvinss** [comment]
I'll review this tomorrow.
Some notes:
* no need to repeat `Buffer.from(@data.uri,'binary').toString('base64')` on `track.coffee`, just use `@data.b64uri`
* `.b64uri` is missing for track, album and artist (I suggest something like [this](`.b64uri`))

**Comment by ethus3h** [comment]
Thank you for your help @kelvinss! I've made a new commit with an attempt at making the changes you advised. :)

**Comment by kelvinss** [comment]
I'm getting an error on `Buffer.from`:
```
/media/DATA/home/kelvin/git/node-spotify-downloader/lib/downloader.coffee:112
                        @data.b64uri = Buffer.from(@data.uri,'binary').toString('base64')
                         ^
TypeError: binary is not a function
```
I'll replace it by `Buffer(@data.uri,'binary')`. Although the docs say it's deprecated… it works.

**Comment by kelvinss** [comment]
Btw, I noticed you didn't commit the compiled JS files. Did you test this code?

**Pull request merged**
